### ISSUE TITLE
why appear driver?

### ISSUE THREAD

**Issue by rarcns** [Lynnette177/Rigel-Apex-Legends#5]
hi!thx best apex code!
After I compiled this, I put the driver in a directory and started it. But even without my driver, [+]Finding apex... is displayed. I wonder why? It's so strange because I thought this code didn't come with a driver. Why is it possible to load without a screwdriver? We can confirm that the driver came out of somewhere. I want to update my drivers, so how can I change them?(sry bad english)

**Comment by Lynnette177** [comment]
No need driver to get pid.
Load your driver on your own

**Comment by rarcns** [comment]
hmm
Does that mean it will load the driver located in the same directory after apex is found?
