### ISSUE TITLE
world to screen issue...?

### ISSUE THREAD

**Issue by rarcns** [Lynnette177/Rigel-Apex-Legends#6]
你好。亲爱的作弊英雄，

我已将驱动程序添加到您发布的此项目中，并更新了偏移量。
但是，e3p根本没有显示，瞄准FOV也显示在左上角哈哈
但是，战斗警报等工作正常......
驱动程序已正常加载并且战斗警报正在运行，因此我们已确定它没有被 EAC 阻止。
我以为这是一个 W2S 问题。
这个发布的来源真的 E3P 有效吗？

**Comment by blitzcheat** [comment]
> 你好。亲爱的作弊英雄，
> 
> 我已将驱动程序添加到您发布的此项目中，并更新了偏移量。 但是，e3p根本没有显示，瞄准FOV也显示在左上角哈哈 但是，战斗警报等工作正常...... 驱动程序已正常加载并且战斗警报正在运行，因此我们已确定它没有被 EAC 阻止。 我以为这是一个 W2S 问题。 这个发布的来源真的 E3P 有效吗？

...............
Because the driver post have no CR3
its not for you lol

**Comment by Lynnette177** [comment]
如果fov在左上角证明你没有获得正确的屏幕宽高比，而一切图形显示都必须正确的屏幕分辨率设置。
